name: flick
description: "A modern movie discovery app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5       # State management
  flutter_card_swiper: ^2.0.3 # Swiper effect
  http: ^1.1.0           # API calls
  shared_preferences: ^2.0.0 # Local persistence
  cached_network_image: ^3.2.0 # Image caching
  shimmer: ^3.0.0        # Skeleton loaders
  share_plus: ^7.0.0     # Share functionality
  connectivity_plus: ^5.0.0 # Connectivity detection
  intl: ^0.19.0          # Internationalization

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
